### ISSUE TITLE
Error 100 : General data error (TransportError(503, 'search_phase_execution_exception'))

### ISSUE THREAD

**Issue by BrianG13** [allegroai/clearml#316]
Hi,

I am using Trains (yes, I know there is a new version - ClearML, and I should upgrade, I am in a middle of a project that ends in 2 weeks and I will make the upgrade).

Meanwhile, I suddenly encounter a problem that I can't access to any experiment on my dashboard.
The error I am receiving on a pop-up is:
![image](https://user-images.githubusercontent.com/51123168/109669865-37113300-7b7b-11eb-966b-ba205bfe6ff7.png)
![image](https://user-images.githubusercontent.com/51123168/109669890-3ed0d780-7b7b-11eb-834f-c9d13c16c9b9.png)

Any idea why this is happening & How can I fix it??

Something I suddenly noticed is that my terminal now is printing something like this:

> 2021-03-02 17:17:24,454 - trains.log - WARNING - failed logging task to backend (1 lines, <500/100: events.add_batch/v1.0 (General data error: err=('1 document(s) failed to index.', [{'index': {'_index': 'events-log-d1bd92a3b039400cbafc60a7a5b1e52b', '_type': 'event', '_id': 'a274e8b6edf243f0bf01b4f05fa38dca', 'status': 503, 'error': {'type': 'unavailable_shards_exception', 'reason': '[events-log-d1bd92a3b039400cbafc60a7a5b1e52b][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[events-log-d1bd92a3b039400cbafc60a7a5b1e52b][0]] containing [index {[events-log-d1bd92a3b039400cbafc60a7a5b1e52b][event][a274e8b6edf243f0bf01b4f05fa38dca], source[{"timestamp": 1614698139485, "type": "log", "task": "c4bf15bf31e74071b1d9c91bb219d91b", "level": "info", "worker": "momo", "msg": "Processing Subject: S1 , Action: Directions , Cameras: (0, 1, 2, 3)\\nProcessing Subject: S1 , Action: Directions 1 , Cameras: (0, 1, 2, 3)\\nProcessing Subject: S1 , Action: Discussion , Cameras: (0, 1, 2, 3)\\nProcessing Subject: S1 , Action: Discussion 1 , Cameras: (0, 1, 2, 3)", "@timestamp": "2021-03-02T15:16:24.445Z", "metric": "", "variant": ""}]}] and a refresh]'}, 'data': {'timestamp': 1614698139485, 'type': 'log', 'task': 'c4bf15bf31e74071b1d9c91bb219d91b', 'level': 'info', 'worker': 'momo', 'msg': 'Processing Subject: S1 , Action: Directions , Cameras: (0, 1, 2, 3)\nProcessing Subject: S1 , Action: Directions 1 , Cameras: (0, 1, 2, 3)\nProcessing Subject: S1 , Action: Discussion , Cameras: (0, 1, 2, 3)\nProcessing Subject: S1 , Action: Discussion 1 , Cameras: (0, 1, 2, 3)', '@timestamp': '2021-03-02T15:16:24.445Z', 'metric': '', 'variant': ''}}}]), extra_info=[events-log-d1bd92a3b039400cbafc60a7a5b1e52b][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[events-log-d1bd92a3b039400cbafc60a7a5b1e52b][0]] containing [index {[events-log-d1bd92a3b039400cbafc60a7a5b1e52b][event][a274e8b6edf243f0bf01b4f05fa38dca], source[{"timestamp": 1614698139485, "type": "log", "task": "c4bf15bf31e74071b1d9c91bb219d91b", "level": "info", "worker": "momo", "msg": "Processing Subject: S1 , Action: Directions , Cameras: (0, 1, 2, 3)\nProcessing Subject: S1 , Action: Directions 1 , Cameras: (0, 1, 2, 3)\nProcessing Subject: S1 , Action: Discussion , Cameras: (0, 1, 2, 3)\nProcessing Subject: S1 , Action: Discussion 1 , Cameras: (0, 1, 2, 3)", "@timestamp": "2021-03-02T15:16:24.445Z", "metric": "", "variant": ""}]}] and a refresh])>)
2021-03-02 17:17:25,142 - trains.log - INFO - Flush timeout 10.0s exceeded, dropping last 26 lines

I will appreciate your help,
Thanks!

**Comment by jkhenning** [comment]
Hi @BrianG13, 

This issue (as well as https://github.com/allegroai/clearml/issues/315) seem to be related to insufficient server disk space causing ES to go into read-only mode or turn active shards into inactive or unassigned.

The disk watermarks controlling the ES free-disk constraints are defined by default as % of the disk space (so it might look to you like you still have plenty of space, but ES thinks otherwise).

If you don't have enough free disk space, clean up files to create more, or resize your partition.
If you do have enough space, you can configure different ES settings in the `docker-compose.yml` file (see [here](https://github.com/allegroai/clearml-server/blob/6434f1028e6e7fd2479b22fe553f7bca3f8a716f/docker/docker-compose.yml#L45) - there are 3 settings, all can be identical)

**Comment by BrianG13** [comment]
Hi @jkhenning , thanks for you reply!

I free a lot of space in my disk as recommended, but I still can't access any log/plot of any experiment, even old experiments that worked.

There is anything I can do to fix this?

**Comment by jkhenning** [comment]
How much disk space did you free up? What is the total size of your disk?

**Comment by BrianG13** [comment]
I free something like 3T. My disk total size is of 7.3T.

I have another question, I want to try and restart my docker, but I am wondering if all the experiments history & logs will be disappear as result of the restart.
![image](https://user-images.githubusercontent.com/51123168/109809254-c4fb2580-7c30-11eb-8bf2-ae1c51fb0ff3.png)

Do you know what is the worst-case scenario for following the above orders?

**Comment by jkhenning** [comment]
> I free something like 3T. My disk total size is of 7.3T.

Can you share the `docker-compose.yml` you're using?

> I have another question, I want to try and restart my docker, but I am wondering if all the experiments history & logs will be disappear as result of the restart.

When deploying the server, you were supposed to create and mount a local data directory (for Trains Server, this is usually `/opt/trains/data`). Assuming the server uses that mounted directory for data storage, you shouldn't lose anything. Making sure this is the case can be done in several ways (here are a few "primitive" ones, in order of ascending confidence 🙂):
- `cd /opt/trains/data` and then listing files in the various subfolders to see there's something there, and that it was recently modified (i.e. `ls -la elastic` and `ls -la mongo`)
- Creating a temporary file inside each data directory (for elastic and mongo) and then executing `bash` inside the respective docker container (e.g. `docker exec -t trains-elastic /bin/bash`), then looking in the internally mounted folder. If the temp file can be seen there, the container is mounted correctly and the data will not vanish on restart

**Comment by BrianG13** [comment]
My docker-compose file:
```
version: "3.6"
services:

  apiserver:
    command:
    - apiserver
    container_name: trains-apiserver
    image: allegroai/trains:0.14.2
    restart: unless-stopped
    volumes:
    - /home/orpat/trains/logs:/var/log/trains
    - /home/orpat/trains/config:/opt/trains/config
    depends_on:
      - redis
      - mongo
      - elasticsearch
      - fileserver
    environment:
      TRAINS_ELASTIC_SERVICE_HOST: elasticsearch
      TRAINS_ELASTIC_SERVICE_PORT: 9200
      TRAINS_MONGODB_SERVICE_HOST: mongo
      TRAINS_MONGODB_SERVICE_PORT: 27017
      TRAINS_REDIS_SERVICE_HOST: redis
      TRAINS_REDIS_SERVICE_PORT: 6379
      TRAINS__apiserver__mongo__pre_populate__enabled: "true"
      TRAINS__apiserver__mongo__pre_populate__zip_file: "/home/orpat/trains/db-pre-populate/export.zip"
    ports:
    - "8008:8008"
    networks:
      - backend

  elasticsearch:
    networks:
      - backend
    container_name: trains-elastic
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      bootstrap.memory_lock: "true"
      cluster.name: trains
      cluster.routing.allocation.node_initial_primaries_recoveries: "500"
      discovery.zen.minimum_master_nodes: "1"
      http.compression_level: "7"
      node.ingest: "true"
      node.name: trains
      reindex.remote.whitelist: '*.*'
      script.inline: "true"
      script.painless.regex.enabled: "true"
      script.update: "true"
      thread_pool.bulk.queue_size: "2000"
      thread_pool.search.queue_size: "10000"
      xpack.monitoring.enabled: "false"
      xpack.security.enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    restart: unless-stopped
    volumes:
    - /home/orpat/trains/data/elastic:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"
fileserver:
    networks:
      - backend
    command:
    - fileserver
    container_name: trains-fileserver
    image: allegroai/trains:latest
    restart: unless-stopped
    volumes:
    - /home/orpat/trains/logs:/var/log/trains
    - /home/orpat/trains/data/fileserver:/mnt/fileserver
    ports:
    - "8081:8081"

  mongo:
    networks:
      - backend
    container_name: trains-mongo
    image: mongo:3.6.5
    restart: unless-stopped
    command: --setParameter internalQueryExecMaxBlockingSortBytes=196100200
    volumes:
    - /home/orpat/trains/data/mongo/db:/data/db
    - /home/orpat/trains/data/mongo/configdb:/data/configdb
    ports:
    - "27017:27017"

  redis:
    networks:
      - backend
    container_name: trains-redis
    image: redis:5.0
    restart: unless-stopped
    volumes:
    - /home/orpat/trains/data/redis:/data
    ports:
    - "6379:6379"

  webserver:
    command:
    - webserver
    container_name: trains-webserver
    image: allegroai/trains:latest
    restart: unless-stopped
    volumes:
    - /home/orpat/trains/logs:/var/log/trains
    depends_on:
      - apiserver
    ports:
    - "8080:80"

networks:
  backend:
    driver: bridge
```

I don't find any `opt/trains/data` folder on my machine. (It wasn't me who installed the Trains framework).
Do you can know where the mount local directory is from `docker-compose.yaml` file?
